services:
  cc-frontend:
    build: .
    # develop:
      # watch:
        # - action: rebuild
        #   path: ./pyproject.toml
    volumes:
      # - .:/app:rw
      # - /app/.venv
      - ./.env:/app/.env
      # - ./db.sqlite:/app/db.sqlite
    ports: 
      - "7860:7860"
